name: Monitor live site and notify Discord

on:
  schedule:
    - cron: '*/3 * * * *' # every 15 minutes
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create monitor config.json from example
        working-directory: tools/monitor-spoilers
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          echo "Creating config.json from config.example.json"
          cp config.example.json config.json
          # Set discordWebhook value using node (setup-node is available)
          node -e "const fs=require('fs'); const p='config.json'; const d=JSON.parse(fs.readFileSync(p)); d.discordWebhook=process.env.DISCORD_WEBHOOK||''; fs.writeFileSync(p, JSON.stringify(d, null, 2));"

      - name: Install monitor dependencies
        working-directory: tools/monitor-spoilers
        run: npm install

      - name: Run monitor (scrape live site and notify Discord)
        working-directory: tools/monitor-spoilers
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          echo "Running monitor..."
          node monitor.js --once

      - name: Commit updated seen.json (if any)
        working-directory: .
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tools/monitor-spoilers/seen.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(monitor): update seen.json by GitHub Actions"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
